class UserExistException(Exception):
    pass


class UserNotFoundException(Exception):
    pass
